version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php74
    container_name: app-php74
    restart: unless-stopped
    environment:
      DB_HOST: db
      DB_PASSWORD: secret
      SESSION_DRIVER: redis
      REDIS_HOST: redis
    volumes:
      - ./:/var/www
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  webserver:
    build:
      context: .
      dockerfile: Dockerfile_Nginx
    image: nginx
    container_name: webserver-nginx
    restart: unless-stopped
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app

  db:
    image: mysql:5.7.22
    container_name: db-5.7.22
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-1


volumes:
  dbdata:
    driver: local

